name: GitHub Stats
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install aiohttp

      - name: Generate GitHub Stats and Process Template
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          python scripts/github_stats.py TEMPLATE.md README.md
        # Ensure no token leakage in logs
        shell: bash

      - name: Commit and push changes
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add github_stats.json README.md
            git commit -m "Update GitHub Stats [skip ci]"
            git push
          fi
